services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  redis:
    image: redis
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "8081:8080"
    environment:
      MODE: standalone
      NACOS_AUTH_TOKEN: dGhpc19pc19hX3ZlcnlfbG9uZ19zZWNyZXRfa2V5XzEyMzQ1Ng==
      NACOS_AUTH_IDENTITY_KEY: serverIdentity
      NACOS_AUTH_IDENTITY_VALUE: security
  dubbo-admin:
    image: apache/dubbo-admin
    container_name: dubbo-admin
    ports:
      - "8082:38080"
    environment:
      - admin.registry.address=zookeeper://zookeeper:2181
      - admin.config-center=zookeeper://zookeeper:2181
      - admin.metadata-report.address=zookeeper://zookeeper:2181
    depends_on:
      - zookeeper
    # environment:
    #   - admin.registry.address=nacos://nacos:8848
    #   - admin.config-center=nacos://nacos:8848
    #   - admin.metadata-report.address=nacos://nacos:8848
    # depends_on:
    #   - nacos
  sentinel-dashboard:
    image: bladex/sentinel-dashboard
    container_name: sentinel-dashboard
    ports:
      - "8858:8858"
    environment:
      - JAVA_OPTS=-Dserver.port=8858
  rocketmq-namesrv:
    image: apache/rocketmq:4.5.1
    container_name: rocketmq-namesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876"  # NameServer 默认端口
    volumes:
      - D:/data/rocketmq/namesrv/logs:/home/rocketmq/logs
    environment:
      - JAVA_OPT_EXT=-Xms512m -Xmx512m  # JVM内存配置
    networks:
      - rocketmq-net
  rocketmq-broker:
    image: apache/rocketmq:4.5.1
    container_name: rocketmq-broker
    command: sh mqbroker -n rocketmq-namesrv:9876 -c /home/rocketmq/conf/broker.conf
    ports:
      - "10909:10909"  # Broker监听端口
      - "10911:10911"  # Broker主端口
      - "10912:10912"  # HA端口
    volumes:
      - D:/data/rocketmq/broker/logs:/home/rocketmq/logs
      - D:/data/rocketmq/conf/broker.conf:/home/rocketmq/conf/broker.conf  # 挂载自定义配置
    environment:
      - JAVA_OPT_EXT=-Xms1g -Xmx1g
    depends_on:
      - rocketmq-namesrv
    networks:
      - rocketmq-net
  rocketmq-dashboard:
    image: styletang/rocketmq-console-ng:1.0.0  # 4.x配套控制台镜像
    container_name: rocketmq-dashboard
    ports:
      - "8080:8080"  # 控制台端口
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
    depends_on:
      - rocketmq-namesrv
    networks:
      - rocketmq-net
networks:
  rocketmq-net:
    driver: bridge