services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  redis:
    image: redis
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "8081:8080"
    environment:
      MODE: standalone
      NACOS_AUTH_TOKEN: dGhpc19pc19hX3ZlcnlfbG9uZ19zZWNyZXRfa2V5XzEyMzQ1Ng==
      NACOS_AUTH_IDENTITY_KEY: serverIdentity
      NACOS_AUTH_IDENTITY_VALUE: security
  dubbo-admin:
    image: apache/dubbo-admin
    container_name: dubbo-admin
    ports:
      - "8082:38080"
    environment:
      - admin.registry.address=zookeeper://zookeeper:2181
      - admin.config-center=zookeeper://zookeeper:2181
      - admin.metadata-report.address=zookeeper://zookeeper:2181
    depends_on:
      - zookeeper
    # environment:
    #   - admin.registry.address=nacos://nacos:8848
    #   - admin.config-center=nacos://nacos:8848
    #   - admin.metadata-report.address=nacos://nacos:8848
    # depends_on:
    #   - nacos
  sentinel-dashboard:
    image: bladex/sentinel-dashboard
    container_name: sentinel-dashboard
    ports:
      - "8858:8858"
    environment:
      - JAVA_OPTS=-Dserver.port=8858